title: 大连海事大学计算机求生指北
subtitle: DLMU CS survival note
description: 一份由在校生整理的 DLMU 计算机类求生笔记
keywords: DLMU, 计算机, 自学, 课程攻略, 新生指南
author: eacnscnj
language: zh-CN
timezone: Asia/Shanghai

url: https://eacnscnj.github.io
root: /
permalink: :category/:title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js

index_generator:
  path: ""
  per_page: 10
  order_by: -date

archive_generator:
  per_page: 10
  yearly: true
  monthly: true

category_generator:
  per_page: 10

tag_generator:
  per_page: 10

feed:
  type: atom
  path: atom.xml
  limit: 20

sitemap:
  path: sitemap.xml

default_category: 未分类
category_map:
tag_map:

date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: date

theme: dlmu
